name: Keep Supabase Alive
on:
  schedule:
    - cron: '0 0 */6 * *'  # Every 6 days at midnight UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Netlify Function
        run: |
          curl -f https://oasispro.netlify.app/.netlify/functions/keep-alive || exit 1